### ISSUE TITLE
OpenJDK Compatability

### ISSUE THREAD

**Issue by thomashillenbrand** [rjurney/Agile_Data_Code_2#104]
Since the OracleJDK is no longer available through the PPA, could we install the OpenJDK version of Java 8 and still build the application without issue?

**Comment by rjurney** [comment]
Shit, really? I just looked up https://www.linuxuprising.com/2019/02/install-any-oracle-java-jdk-version-in.html and it looks promising. 

I have to fix this thing up for a class in a couple weeks, so I'll be doing some work on it. By all means an option to use OpenJDK would be awesome. Are you volunteering? :)

**Comment by thomashillenbrand** [comment]
I installed OpenJDK and continued on with the rest of the installations without issue. I was planning on working thru the book now, and would be happy to let you know if I run into any issues.

**Comment by rjurney** [comment]
Would you mind submitting the steps you used as an edit to the book's
install code? I would test it and would really appreciate it, as would
others!

Thanks,
Russell Jurney @rjurney <http://twitter.com/rjurney>
russell.jurney@gmail.com LI <http://linkedin.com/in/russelljurney> FB
<http://facebook.com/jurney> datasyndrome.com

**Comment by thomashillenbrand** [comment]
Sure thing, I'll try to do it tonight or tomorrow.

**Comment by IvanVigor** [comment]
Thank you for your feedbacks @rjurney.
I have modified in my directory your script `sudo apt-get install openjdk-8-jdk `with `sudo apt-get install -y openjdk-8-jdk`.

**Comment by rjurney** [comment]
Fixed both AWS and vagrant scripts

**Comment by rjurney** [comment]
Thanks, this works.
