### ISSUE TITLE
Spark 2.2.1 no longer available @ http://apache.mirrors.lucidnetworks.net

### ISSUE THREAD

**Issue by arnaudbouffard** [rjurney/Agile_Data_Code_2#109]
Should be available from Apache Archive though, currently looking into in ec2_bootstrap.sh changing

http://apache.mirrors.lucidnetworks.net/spark/spark-2.2.1/spark-2.2.1-bin-hadoop2.7.tgz

into

http://archive.apache.org/dist/spark/spark-2.2.1/spark-2.2.1-bin-hadoop2.7.tgz

Will do pull request if all works.

**Comment by rjurney** [comment]
Thanks!

**Comment by rjurney** [comment]
Just fixed this, using 2.4.2 now.
