### ISSUE TITLE
issue with manual_install.sh

### ISSUE THREAD

**Issue by elmonisch** [rjurney/Agile_Data_Code_2#115]
Hi, I am having a problem when executing manual_install.sh. I didnt set up any vagrant, just git clone and setup `PROJECT_HOME` and run `./manual_install.sh`. All is done in digitalocean ubuntu18 16gb ram. 

Would you help me with that, please?

**Comment by rjurney** [comment]
I’m going to remove manual_install since it hasn’t been updated in a long time and I don’t support it. I do support the Vagrant environment, so my suggestion is to either run Vagrant on digital ocean or adapt the Vagrant script (bootstrap.sh) to work for you.

**Comment by elmonisch** [comment]
Still didnt work, what I did was : 

- Get the droplets 16gb ubuntu18
- sudo apt update and upgrade
- git clone ...
- sudo apt install virtualbox
- sudo apt install vagrant
- cd Agile_Data_Code_2
- vagrant up

The errors were :  
```

vagrant:
* The following settings shouldn't exist: plugins

Vagrant:
* Unknown configuration section 'disksize'.

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vagrant:
* The following settings shouldn't exist: plugins

Vagrant:
* Unknown configuration section 'disksize'.
```

**Comment by rjurney** [comment]
Can you check the version of vagrant you're running? Run this command and print the output.

```bash
vagrant --version
```

Oh, btw, before `vagrant up` you need to run `vagrant init`. Let me edit the docs now to add this...

**Comment by rjurney** [comment]
@elmonisch Updated the previous comment, in case you don't see it.

**Comment by elmonisch** [comment]
Vagrant version : `2.0.2`
vagrant init : ``Vagrantfile` already exists in this directory. Remove it before running `vagrant init`.`
vagrant box update : `==> default: Box 'ubuntu/bionic64' not installed, can't check for updates.`

Still couldn't go with it..

**Comment by rjurney** [comment]
Install vagrant 2.2.4 and try again. I was mistaken about `vagrant init`, sorry. I think things will work for you once you do that.

**Comment by elmonisch** [comment]
Closed thanks!

**Comment by rjurney** [comment]
Happy to help! It’s frustrating how out of date Ubuntu packages can get.
