### ISSUE TITLE
Request to have a local installation

### ISSUE THREAD

**Issue by elmonisch** [rjurney/Agile_Data_Code_2#117]
I would like a make a video request regarding the step by step local installation inside a personal machine especially for those who bought your course. I dont have much money to rent the machine on AWS and other cloud provider. Thanks!

**Comment by rjurney** [comment]
Check out the vagrant instructions, that’s what they are. If you don’t want to use that, copy the commands from the vagrant file and use those. A manual install is harder, would vary per reader, there’s no way I can support that.

When did you buy the course? It should be taken down.
