### ISSUE TITLE
ch04: cannot find ../data/on_time_performance.jsonl.gz/

### ISSUE THREAD

**Issue by txzhou** [rjurney/Agile_Data_Code_2#118]
Cannot find the `../data/on_time_performance.jsonl.gz/` file while running the notebook.
There's no command to downloaded this file in either `./download.sh` or `./ch04/download.sh`
There's also no command to write this file in `./ch04/Collecting_and_Displaying_Records.ipynb`

Because of this, cannot get the correct results in "## Sizing Up Our Data" and "## Inspecting the Data"

**Comment by rjurney** [comment]
@txzhou I can fix this Monday

**Comment by rjurney** [comment]
This should be fixed.
