### ISSUE TITLE
EC2 won't connect to internet 

### ISSUE THREAD

**Issue by aashnashroff1** [rjurney/Agile_Data_Code_2#122]
Failed to connect to https://changelogs.ubuntu.com/meta-release. Check your Internet connection or proxy settings

ubuntu@ip-172-31-5-185:~$ sudo apt update
Err:1 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu cosmic InRelease                                                   
  Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.204.122), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.168.13.207), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.199.72.88), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.192.197), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.168.29.123), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.22.77), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.7.22), connection timed out
Err:2 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu cosmic-updates InRelease                                        
  Unable to connect to ap-south-1.ec2.archive.ubuntu.com:http:
Err:3 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu cosmic-backports InRelease
  Unable to connect to ap-south-1.ec2.archive.ubuntu.com:http:
Err:4 http://security.ubuntu.com/ubuntu cosmic-security InRelease
  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.14), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.174), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.173), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.162), connection timed out
Reading package lists... Done                         
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/dists/cosmic/InRelease  Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.204.122), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.168.13.207), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.199.72.88), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.192.197), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.168.29.123), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.22.77), connection timed out Could not connect to ap-south-1.ec2.archive.ubuntu.com:80 (54.248.7.22), connection timed out
W: Failed to fetch http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/dists/cosmic-updates/InRelease  Unable to connect to ap-south-1.ec2.archive.ubuntu.com:http:
W: Failed to fetch http://ap-south-1.ec2.archive.ubuntu.com/ubuntu/dists/cosmic-backports/InRelease  Unable to connect to ap-south-1.ec2.archive.ubuntu.com:http:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/cosmic-security/InRelease  Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::14). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::21). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1560:8001::11). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1360:8001::17). - connect (101: Network is unreachable) Cannot initiate the connection to security.ubuntu.com:80 (2001:67c:1562::19). - connect (101: Network is unreachable) Could not connect to security.ubuntu.com:80 (91.189.91.14), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.23), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.149), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.174), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.26), connection timed out Could not connect to security.ubuntu.com:80 (91.189.91.24), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.31), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.173), connection timed out Could not connect to security.ubuntu.com:80 (91.189.88.162), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.

ubuntu@ip-172-31-5-185:~$ pyspark
pyspark: command not found
ubuntu@ip-172-31-5-185:~$ pip install pyspark

Command 'pip' not found, but can be installed with:

sudo apt install python-pip

ubuntu@ip-172-31-5-185:~$ sudo apt install python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pip
ubuntu@ip-172-31-5-185:~$

**Comment by rjurney** [comment]
@aashnashroff1 looks like there was a network issue. I take it that it went away?
