### ISSUE TITLE
kafka not working in Vagrant 

### ISSUE THREAD

**Issue by danovalla** [rjurney/Agile_Data_Code_2#125]
Hi @rjurney , I don't know if you're still supporting Vagrant, but in case you are, the kafka_2.11-2.1.1.tgz file is no longer working. I replaced it for  

curl -Lko /tmp/kafka_2.11-2.1.1.tgz https://www-us.apache.org/dist/kafka/2.4.1/kafka_2.11-2.4.1.tgz

and it seems to work fine so far. Hope it helps

**Comment by rjurney** [comment]
Thanks!

**Comment by rjurney** [comment]
@danovalla this should be fixed in the new `Dockerfile` / `docker-compose` setup!
