### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by kayne10** [rjurney/Agile_Data_Code_2#126]
This initially fails because the Java sdk is unavailable. I have a local zip file of the sdk and made some changes to the docker file so that it can it attempt to get Java installed and this worked. However the command pip install -r requirements.txt causes the build to fail.

ERROR: Cannot uninstall 'SQLAlchemy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
The command '/bin/sh -c pip install --upgrade pip &&     pip install -r requirements.txt' returned a non-zero code: 1

I think this happens because there are incompatible versions of flask

ERROR: apache-airflow 1.10.10 has requirement flask<2.0,>=1.1.0, but you'll have flask 0.11.1 which is incompatible.
ERROR: apache-airflow 1.10.10 has requirement jinja2<2.11.0,>=2.10.1, but you'll have jinja2 2.8 which is incompatible.
ERROR: apache-airflow 1.10.10 has requirement requests<3,>=2.20.0, but you'll have requests 2.11.1 which is incompatible.
ERROR: flask-appbuilder 1.13.1 has requirement click<8,>=6.7, but you'll have click 6.6 which is incompatible.
ERROR: flask-appbuilder 1.13.1 has requirement Flask<2,>=0.12, but you'll have flask 0.11.1 which is incompatible.
ERROR: flask-appbuilder 1.13.1 has requirement marshmallow<2.20,>=2.18.0, but you'll have marshmallow 3.5.2 which is incompatible.
ERROR: flask-jwt-extended 3.24.1 has requirement Flask>=1.0, but you'll have flask 0.11.1 which is incompatible.
ERROR: flask-jwt-extended 3.24.1 has requirement Werkzeug>=0.14, but you'll have werkzeug 0.11.11 which is incompatible.
ERROR: flask-caching 1.3.3 has requirement Werkzeug>=0.12, but you'll have werkzeug 0.11.11 which is incompatible.
ERROR: pendulum 1.4.4 has requirement python-dateutil<3.0.0.0,>=2.6.0.0, but you'll have python-dateutil 2.5.3 which is incompatible.
ERROR: jsonschema 3.2.0 has requirement six>=1.11.0, but you'll have six 1.10.0 which is incompatible.

**Comment by hanbyul-kim** [comment]
I resolved all the related Docker issues at #129 . All the code snippets in the chapter 02 were tested. They're running smoothly!

**Comment by rjurney** [comment]
I am making a new and working Docker image and am removing the scripts that run the entire system as no longer needed.

**Comment by rjurney** [comment]
@hanbyul-kim I hope this was fixed last year!
