### ISSUE TITLE
issue running on ec2: ERROR: JAVA_HOME /usr/lib/jvm/java-8-oracle does not exist

### ISSUE THREAD

**Issue by JelenaSparic** [rjurney/Agile_Data_Code_2#127]
Same issue again. 
Running EC2 instance by using ec2.sh, after connecting the error message: 'ERROR: JAVA_HOME /usr/lib/jvm/java-8-oracle does not exist.' shows up. Seems all application depends on Java is not installed as in the 'kafka/' and 'spark/' are both empty.

_Originally posted by @JelenaSparic in https://github.com/rjurney/Agile_Data_Code_2/issues/99#issuecomment-640258995_

**Comment by rjurney** [comment]
@JelenaSparic sorry for taking so long to reply but you can now use the `Dockerfile` via `docker-compose`.
