### ISSUE TITLE
ssh tunnel creation connection timed out / service not found

### ISSUE THREAD

**Issue by dhruvikhankhoje** [rjurney/Agile_Data_Code_2#140]
After running ec2.sh, I ran the ec2_create_tunnel.sh command, and got this result:

$ ./ec2_create_tunnel.sh

This script will create an ssh tunnel between the ec2 host's port 5000 and your local port 5000.
This will enable you to view web applications you run from ex. Agile_Data_Code_2/ch08/web to be viewed at http://localhost:5000
Note: the tunnel will run in the background, and will die when you terminate the EC2 instance.

First we will forward the port the web appliations use...
Forwarding the remote machine's port 5000 to the local port 5000, which you can then access at http://localhost:5000
Executing: ssh -N -i ./agile_data_science.pem -o StrictHostKeyChecking=no -L 5000:localhost:5000 ubuntu@$EC2_HOSTNAME &

Next we will forward the port the Jupyter Notebooks use...
Forwarding the remote machine's port 8888 to the local port 8888, which you can then access at http://localhost:8888
Executing: ssh -N -i ./agile_data_science.pem -o StrictHostKeyChecking=no -L 8888:localhost:8888 ubuntu@$EC2_HOSTNAME &

Next we will forward the port that Airflow uses...
Forwarding the remote machine's port 8080 to the local port 8080, which you can then access at http://localhost:8080
Executing: ssh -N -i ./agile_data_science.pem -o StrictHostKeyChecking=no -L 8080:localhost:8080 ubuntu@$EC2_HOSTNAME &

dhruv@DESKTOP-RL5M8G7 MINGW64 ~/OneDrive/Desktop/Agile_Data_Code_2-master
$ ssh: connect to host ec2-44-234-19-200.us-west-2.compute.amazonaws.com port 22: Connection timed out
ssh: connect to host ec2-44-234-19-200.us-west-2.compute.amazonaws.com port 22: Connection timed out
ssh: connect to host ec2-44-234-19-200.us-west-2.compute.amazonaws.com port 22: Connection timed out
././ec2_kill_tunnel.sh

On doing the same process again, I got this output:
$ ./ec2_create_tunnel.sh
./ec2_create_tunnel.sh: line 4: [: too many arguments

This script will create an ssh tunnel between the ec2 host's port 5000 and your local port 5000.
This will enable you to view web applications you run from ex. Agile_Data_Code_2/ch08/web to be viewed at http://localhost:5000
Note: the tunnel will run in the background, and will die when you terminate the EC2 instance.

First we will forward the port the web appliations use...
Forwarding the remote machine's port 5000 to the local port 5000, which you can then access at http://localhost:5000
Executing: ssh -N -i ./agile_data_science.pem -o StrictHostKeyChecking=no -L 5000:localhost:5000 ubuntu@$EC2_HOSTNAME &

Next we will forward the port the Jupyter Notebooks use...
Forwarding the remote machine's port 8888 to the local port 8888, which you can then access at http://localhost:8888
Executing: ssh -N -i ./agile_data_science.pem -o StrictHostKeyChecking=no -L 8888:localhost:8888 ubuntu@$EC2_HOSTNAME &

Next we will forward the port that Airflow uses...
Forwarding the remote machine's port 8080 to the local port 8080, which you can then access at http://localhost:8080
Executing: ssh -N -i ./agile_data_science.pem -o StrictHostKeyChecking=no -L 8080:localhost:8080 ubuntu@$EC2_HOSTNAME &

: Name or service not knownname ec2-34-222-203-121.us-west-2.compute.amazonaws.com
: Name or service not knownname ec2-34-222-203-121.us-west-2.compute.amazonaws.com
: Name or service not knownname ec2-34-222-203-121.us-west-2.compute.amazonaws.com

What can i do to fix this?

**Comment by rjurney** [comment]
@dhruvikhankhoje we no longer use EC2 because of issues like this one. You can use the `Dockerfile` via `docker-compose` to run all services. Much easier!
