### ISSUE TITLE
./download_weather.sh file doesn't download weather data

### ISSUE THREAD

**Issue by giedreOk** [rjurney/Agile_Data_Code_2#154]
When I run download_weather.sh script, I get the following error for each file in the cycle:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   261    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   428  100   428    0     0     13      0  0:00:32  0:00:30  0:00:02   105
Archive:  /tmp/QCLCD20151.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/QCLCD20151.zip or
        /tmp/QCLCD20151.zip.zip, and cannot find /tmp/QCLCD20151.zip.ZIP, period.
gzip: can't stat: 20151*.txt (20151*.txt): No such file or directory
```

Googling for the "End-of-central-directory signature not found" did not help, I have tried suggestions from this link and some more: https://askubuntu.com/questions/54904/unzip-error-end-of-central-directory-signature-not-found

Running the command in Jupyter Lab on Macbook Pro M1 chip.
Any help would be greatly appreciated.

**Comment by rjurney** [comment]
@giedreOk check out the file: https://github.com/rjurney/Agile_Data_Code_2/blob/master/download_weather.sh

I see it expects https://www.ncdc.noaa.gov/orders/qclcd/QCLCD201501.zip to work and unfortunately it gets a 503 error - service unavailable. I hope it comes back in service and will research other ways to get that data. I will contact the National Centers for Environmental Information to see where this data is now accessible.

Stay tuned!

**Comment by rjurney** [comment]
Unfortunately this data is offline. I found where it is supposed to be here: https://ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00679 however it isn't there... that IP is not any longer around :( 

Closing because this part of the book isn't salvageable. If we do an update, I will fix this!
