### ISSUE TITLE
ch06/enrich_airlines_wikipedia.py 

### ISSUE THREAD

**Issue by md6nguyen** [rjurney/Agile_Data_Code_2#18]
In ch06/enrich_airlines_wikipedia.py throws error because it cannot find the file 'data/our_airlines.jsonl'. I checked the data directory I only found the file 'data/our_airlines.json'
>>> our_airlines = utils.read_json_lines_file('data/our_airlines.jsonl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/Agile_Data_Code_2/lib/utils.py", line 29, in read_json_lines_file
    f = codecs.open(path, "r", "utf-8")
  File "/home/ubuntu/anaconda/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'data/our_airlines.jsonl'

**Comment by rjurney** [comment]
There is a line earlier in chapter 6, that says to: cp data/our_airlines.json/part* data/our_airlines.jsonl

But I will add a line that does this in the script.

See: https://github.com/rjurney/Agile_Data_Code_2/commit/b99aa1948c48b62e0898ac14c36205450aaf9811
