### ISSUE TITLE
Miniconda doesn't include jupyter

### ISSUE THREAD

**Issue by seajosh** [rjurney/Agile_Data_Code_2#20]
bootstrap.sh:27

**Comment by seajosh** [comment]
using vagrant:

sudo chown -R vagrant /home/vagrant/anaconda
sudo chgrp -R vagrant /home/vagrant/anaconda
conda install jupyter

**Comment by seajosh** [comment]
jupyter was removed from the ipython distribution and moved to its own package

https://ipython.org/

**Comment by rjurney** [comment]
Addressed in the pull request and the commit I just pushed.

https://github.com/rjurney/Agile_Data_Code_2/pull/13
and
https://github.com/rjurney/Agile_Data_Code_2/commit/d362753c5a46e530ac92e08172495666872120e7
