### ISSUE TITLE
Vagrant / jupyter port forwarding

### ISSUE THREAD

**Issue by seajosh** [rjurney/Agile_Data_Code_2#21]
Windows 10
Windows Defender: off

Problem:
After provisioning a Vagrant guest and running `jupyter notebook`, HTTP requests weren't forwarded to Jupyter on the Vagrant guest.

Solution:
jupyter was binding on localhost/127.0.0.1; therefore, vagrant couldn't forward the requests because it couldn't find a listener on the guest IP.

Here's a command for running Jupyter so it binds on vagrant's guest IP instead of localhost/127.0.0.1 :

`jupyter notebook --ip=0.0.0.0`

This allows vagrant's port forwarding to work correctly.

**Comment by rjurney** [comment]
Thanks, I added this to the boot scripts.
