### ISSUE TITLE
pyspark example bug

### ISSUE THREAD

**Issue by seajosh** [rjurney/Agile_Data_Code_2#23]
Ch02 "Collecting Data", p37

problem:
Assuming user in is in ch02 directory per text 

`csv_lines = sc.textFile("data/example.csv")`
incorrect file path

solution:
`csv_lines = sc.textFile("../data/example.csv")`

**Comment by rjurney** [comment]
Where does it say to be in ch02 directory? Or is this just assumed? Actually, all code has to be executed from $PROJECT_HOME. Any tips for how I could better express this?

**Comment by seajosh** [comment]
Below is what made me go to the ch02 dir

"To get an iPython shell with PySpark, make sure
you’re in the ch02 directory and run PYSPARK_DRIVER_PYTHON=ipython pyspark ."

**Comment by rjurney** [comment]
Shit. Thanks!

**Comment by rjurney** [comment]
Updated the book, thanks.
