### ISSUE TITLE
EC2 instance requires instructions how to make Flask web pages available externally

### ISSUE THREAD

**Issue by md6nguyen** [rjurney/Agile_Data_Code_2#25]
For EC2 instance, I cannot view Flask web pages even when I add port 5000 to the Security Group. 
There should be instruction in EC2 set up on how to view Flask pages, maybe using ssh tunnels?

**Comment by rjurney** [comment]
Thank you, yes I have been testing an ssh tunnel command and will get back to you with something that works!

**Comment by rjurney** [comment]
@md6nguyen Working on this now!

**Comment by rjurney** [comment]
@md6nguyen I have completely rewritten the EC2 scripts. They are now much easier to use, have multi-region support, and I have battle tested them. There are also instructions in the message you see when you ssh into the machine, and we print ssh instructions once we instantiate a new instance. Check it out! 

Please re-open if you have problems :)

**Comment by md6nguyen** [comment]
I just tried it out and it worked great 👍 Thanks!
