### ISSUE TITLE
The vagrant install script for Virtual PC stopped after Jupyter start

### ISSUE THREAD

**Issue by kelvinksau** [rjurney/Agile_Data_Code_2#26]
Hi

I run the 'vagrant up' command  the vagrant script stop after Jupyter started as below.  Is it an expected behaviour ?

==> default: writing new private key to '/home/ubuntu/certs/mycert.pem'
==> default: /home/ubuntu/certs/mycert.pem: No such file or directory
==> default: 140332068832928:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/home/ubuntu/certs/mycert.pem','w')
==> default: 140332068832928:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
==> default: [I 15:24:19.003 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
==> default: [I 15:24:19.097 NotebookApp] Serving notebooks from local directory: /home/vagrant
==> default: [I 15:24:19.097 NotebookApp] 0 active kernels
==> default: [I 15:24:19.097 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/?token=4015c82d2c7f00926f6066101ad77cfc8e14667b9959ca93
==> default: [I 15:24:19.098 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
==> default: [W 15:24:19.098 NotebookApp] No web browser found: could not locate runnable browser.
==> default: [C 15:24:19.098 NotebookApp]
==> default:
==> default:     Copy/paste this URL into your browser when you connect for the first time,
==> default:     to login with a token:
==> default:         http://0.0.0.0:8888/?token=4015c82d2c7f00926f6066101ad77cfc8e14667b9959ca93

**Comment by rjurney** [comment]
Looking into this now...

**Comment by rjurney** [comment]
@kelvinksau Can you tell me what operating system you are running this on? Local or in the cloud?

**Comment by rjurney** [comment]
Closing because he never replied.
