### ISSUE TITLE
aws/ec2_bootstrap.sh should log progress in a log file

### ISSUE THREAD

**Issue by md6nguyen** [rjurney/Agile_Data_Code_2#27]
The bootstrap script aws/ec2_bootstrap.sh takes around 15 minutes to complete. I think the script should log the progress in a log file with a confirmation when the setup is complete. User can then check the log and wait until it is complete so that they won't start playing when the set up is in progress.

**Comment by rjurney** [comment]
@md6nguyen I implemented this in commit https://github.com/rjurney/Agile_Data_Code_2/commit/5720f0237fc44885cb55c1a757369b52a0a26d90
