### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'map'

### ISSUE THREAD

**Issue by kelvinksau** [rjurney/Agile_Data_Code_2#28]
The following program would not work under Spark 2.0

`Use .rdd.map:`

**DataFrame.map has been removed in Spark 2.**

# Load the parquet file
on_time_dataframe = spark.read.parquet('data/on_time_performance.parquet')
on_time_dataframe.registerTempTable("on_time_performance")

# Dump the unneeded fields
tail_numbers = on_time_dataframe.map(lambda x: x.TailNum)
tail_numbers = tail_numbers.filter(lambda x: x != '')

# distinct() gets us unique tail numbers
unique_tail_numbers = tail_numbers.distinct()

# now we need a count() of unique tail numbers
airplane_count = unique_tail_numbers.count()
print("Total airplanes: {}".format(airplane_count))

**Comment by rjurney** [comment]
Sorry about this, I fixed this a few days ago. Please re-open if you have any more issues.

**Comment by kelvinksau** [comment]
Do you have a script to generate faa_tail_number_inquiry.jsonl ? I can see any python to handle this ? 

Thx for the great work
