### ISSUE TITLE
  File "/home/ubuntu/Agile_Data_Code_2/ch06/web/search_helpers.py", line 28     except AttributeError, e:

### ISSUE THREAD

**Issue by kelvinksau** [rjurney/Agile_Data_Code_2#29]
File "report_flask.py", line 9, in <module>
    import search_helpers
  File "/home/ubuntu/Agile_Data_Code_2/ch06/web/search_helpers.py", line 28
    except AttributeError, e:

----
In python3 the raise syntax no longer accepts comma-separated arguments.

Use as instead:

**Comment by rjurney** [comment]
Thanks you, resolved in https://github.com/rjurney/Agile_Data_Code_2/commit/19de9d4f01266f95c03f85e8534d7c81545bf5a0
