### ISSUE TITLE
Missing of faa_tail_number_inquiry.jsonl file

### ISSUE THREAD

**Issue by kelvinksau** [rjurney/Agile_Data_Code_2#31]
Is it possible to provide the script to generate the faa_tail_number_inquiry.jsonl file, as the file is required for programs at other chapter.

It is mentioned in the book under "Evaluating Enriched Data"
===
Now that we’ve got our tail number data in data/faa_tail_number_inquiry.json', lets see what we’ve got. First we want to know how many records did we successfully achieve, both in raw form and as a percent?"
===

**Comment by nickrosener** [comment]
+1 for this. The book says "don't scrape the FAA site" then doesn't give us the scraped data.

**Comment by rjurney** [comment]
Oh shit! Sorry about that. Let me make sure it is added...

**Comment by rjurney** [comment]
I added this data in https://github.com/rjurney/Agile_Data_Code_2/commit/7393edbcb27831af4f5de4e17abe79bb78f37b20 and I added the scraping script in https://github.com/rjurney/Agile_Data_Code_2/commit/a45c04ba16a5424189f2df580e691e6336f62a82
