### ISSUE TITLE
It's nice to have a script to clean up EC2 resource

### ISSUE THREAD

**Issue by md6nguyen** [rjurney/Agile_Data_Code_2#32]
It's nice to have a script to clean up EC2 resources (i.e. instance, volume, security group, key pair) after user is done with the instance. 

Currently in ec2.sh "Ebs":{"DeleteOnTermination":false} so even when user terminated instance the EBS volume is still available and will cost user $$$. I actually think Ebs should be automatically deleted when instance is terminated. What's the point of keeping the volume when all the data are totally reproducible? But if it is decided to be like this the clean up script is quite important to avoid unnecessary charge.

**Comment by rjurney** [comment]
Fixed in https://github.com/rjurney/Agile_Data_Code_2/commit/6f3a9913737bc87e8fe05388af7bae4df1100668

Thanks!
