### ISSUE TITLE
Bootstrap Install Fails on Jupyter Notebook Install

### ISSUE THREAD

**Issue by jaykinghorn** [rjurney/Agile_Data_Code_2#34]
When I try and install the dependencies using the Bootstrap.sh file, I keep getting hung up on the Jupyter Notebook install with the following error:
[C 14:26:04.850 NotebookApp] Bad config encountered during initialization:
[C 14:26:04.850 NotebookApp] Unrecognized flag: '--allow-root'

https://github.com/jupyter/notebook/issues/1539

A quick google search brings me to a similar error with Docker files, though I don't know where to go next to troubleshoot/resolve this. 

Do you have any advice? 

Thanks,

Jay

**Comment by rjurney** [comment]
You can remove the `--allow-root` argument and it should work.

In commit https://github.com/rjurney/Agile_Data_Code_2/commit/8f988fc5df93fe19e08dc8ba87e615fe80d49758 I added jupyter notebooks to the requirements.txt and set the version to 5.0.0, which does have `--alow-root` as an option. This should resolve the issue, please reopen if it does not.
