### ISSUE TITLE
Lines 38-39 of aws/ec2_bootstrap.sh are inconsistent

### ISSUE THREAD

**Issue by mileserickson** [rjurney/Agile_Data_Code_2#39]
Line 38 is a comment indicating that Spark will use 8GB of RAM, but the following line sets spark.driver.memory to 25GB. One or the other needs to be updated for consistency.

> 38: # Give Spark 8GB of RAM, used Python3
> 39: echo "spark.driver.memory 25g" | sudo tee -a $SPARK_HOME/conf/spark-defaults.conf

**Comment by rjurney** [comment]
How nice to get a pull request! Thanks, merged :)
