### ISSUE TITLE
ec2.sh no hostname created

### ISSUE THREAD

**Issue by BMamball** [rjurney/Agile_Data_Code_2#42]
No hostname created after running ec2.sh

**Comment by MiksLynx** [comment]
Same here

**Comment by josecyc** [comment]
same here, have a solution? and it makes me unable to create a tunnel and see the web apps

**Comment by rjurney** [comment]
@BMamball @MiksLynx @josecyc Can you please paste the complete output of [ec2.sh](ec2.sh) so I can debug the issue?

**Comment by johntekdek** [comment]
hi 

I ran  ssh -i ./agile_data_science.pem ubuntu@

and i got the following:

ssh: connect to host  port 22: Connection refused


what do i do?

**Comment by johntekdek** [comment]
Detecting external IP address ...
./ec2.sh: line 49: dig: command not found
Authorizing port 22 to your external IP () in security group 'agile_data_science' ...

An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupIngress operation: CIDR block C:/Program Files/Git/32 is malformed

**Comment by Francososa** [comment]
I am having the same problem. Also, doesn't set `aws configure` fields. Here is my output: 
[ec2_sh_output.txt](https://github.com/rjurney/Agile_Data_Code_2/files/1220698/ec2_sh_output.txt)

**Comment by Francososa** [comment]
Configuring the [AWS CLI](http://docs.aws.amazon.com/cli/latest/reference/configure/) options solved this issue for me. You will first have to create an IAM user to get the necessary: 
`AWS Access Key ID [None]: accesskey`
`AWS Secret Access Key [None]: secretkey`

**Comment by rjurney** [comment]
You have to setup `aws configure` yourself. I am not sure how to automate this, but it is a common source of problems :(

**Comment by rjurney** [comment]
Closing for staleness.

**Comment by mrminpeng** [comment]
[ec2-user@ip-172-31-36-232 Agile_Data_Code_2]$ ssh -i ./agile_data_science.pem ubuntu@
ssh: Could not resolve hostname : Name or service not known

I got this problem as above, suspect maybe due to no region set in aws configure, but how to fix?

Detecting the default region...
The default region is ''
Determining the image ID to use according to region...
The image for region '' is '' ...
