### ISSUE TITLE
Chapter 8 test_classification_api.sh is wrong

### ISSUE THREAD

**Issue by kelvinksau** [rjurney/Agile_Data_Code_2#43]
It should write as follow 

curl -XPOST 'http://localhost:5000/flights/delays/predict/classify' \
  -F 'DepDelay=5.0' \
  -F 'Carrier=AA' \
  -F 'FlightDate=2016-12-23' \
  -F 'Dest=ATL' \
  -F 'FlightNum=1519' \
  -F 'Origin=SFO' \
| json_pp

FlightDate instead of Date

**Comment by rjurney** [comment]
Fixed in https://github.com/rjurney/Agile_Data_Code_2/commit/5215bc16d8424a87cb96492257f5552e2cc6f05d

@kelvinksau Thanks!
