### ISSUE TITLE
Issues with Vagrant Instance

### ISSUE THREAD

**Issue by balasvasan** [rjurney/Agile_Data_Code_2#46]
Hi:

i get this following error during vagrant up. anyone seen this before?

<img width="1144" alt="screen shot 2017-07-06 at 11 31 07 pm" src="https://user-images.githubusercontent.com/12105100/28082056-f5880df8-6636-11e7-8ac9-08461817bcc3.png">
<img width="1383" alt="screen shot 2017-07-06 at 11 28 25 pm" src="https://user-images.githubusercontent.com/12105100/28082057-f5895078-6636-11e7-8e40-46a992d46104.png">
<img width="1068" alt="screen shot 2017-07-06 at 6 17 28 pm" src="https://user-images.githubusercontent.com/12105100/28082058-f594d538-6636-11e7-9602-08433eb87a2d.png">

**Comment by nickrosener** [comment]
I'm also getting the error in the first screenshot, using OSX. It's messing with the configuration of the token in the jupyter notebook. Still tracking down the cause.

**Comment by nickrosener** [comment]
I think I fixed the notebook error in #47

**Comment by rjurney** [comment]
Working on this...

**Comment by balasvasan** [comment]
Thanks. Please let me know if you need any help with testing .. Happy to
chime in.


Cheers
Balaji

**Comment by rjurney** [comment]
I think I am going to have to deprecate the Vagrant system. There is not enough RAM on most computers to run the system completely, and I don't have time to keep both up to date. You will have to use the ec2 scripts. Sorry :( I will update the book accordingly.

**Comment by balasvasan** [comment]
No issues. Sticking with a Cloud solution actually is in line with the intent of book. As a suggestion If you can add 2 blogs around deploying this in Azure and another one on containerization / Docker, it would complete the trifecta of Cloud, Big Data and Data Science. - Cheers - Balaji
