### ISSUE TITLE
ch08/extract_features.py is not working

### ISSUE THREAD

**Issue by kelvinksau** [rjurney/Agile_Data_Code_2#49]
Seems missed the section to create SparkContext via findspark

**Comment by rjurney** [comment]
Fixed in https://github.com/rjurney/Agile_Data_Code_2/commit/323dc4fbe20ef6c663327dd5f94c999a5f1eadd2

@kelvinksau Can you please test?

**Comment by rjurney** [comment]
Closing for staleness.
