### ISSUE TITLE
ch06/add_name_to_airlines.py throws error

### ISSUE THREAD

**Issue by md6nguyen** [rjurney/Agile_Data_Code_2#5]
The following error is thrown when running ch06/add_name_to_airlines.py

>>> airlines = spark.read.format('com.databricks.spark.csv')\
...   .options(header='false', nullValue='\N')\
...   .load('data/airlines.csv')
  File "<stdin>", line 2
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: malformed \N character escape

**Comment by rjurney** [comment]
Resolved, please pull latest and retry.

**Comment by md6nguyen** [comment]
Thanks, here's a new one:
https://github.com/rjurney/Agile_Data_Code_2/issues/18
