### ISSUE TITLE
Airflow not working

### ISSUE THREAD

**Issue by josecyc** [rjurney/Agile_Data_Code_2#51]
Whenever I try to run the command `$ airflow` I get the following:

This happens with any airflow command

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/bin/airflow", line 17, in <module>
    from airflow import configuration
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/airflow/__init__.py", line 29, in <module>
    from airflow import configuration as conf
  File "/home/ubuntu/anaconda/lib/python3.5/site-packages/airflow/configuration.py", line 769, in <module>
    with open(TEST_CONFIG_FILE, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/airflow/unittests.cfg'
```

can someone please tell me what mistake I might be making.

I am running the ec2 instance...

**Comment by RayBrown1** [comment]
Looks like the account running airflow does not have permission to write to the file "/home/ubuntu/airflow/unittests.cfg" which makes sense because the "ubuntu" user probably owns that file.

**Comment by rjurney** [comment]
@RayBrown1 Thank you, I can reproduce. Working on this...

**Comment by rjurney** [comment]
@RayBrown1 I get the same thing. Run this command (from [aws/ec2_bootstrap.sh](aws/ec2_bootstrap.sh) to fix it:

```
sudo chown -R ubuntu /home/ubuntu/airflow
sudo chgrp -R ubuntu /home/ubuntu/airflow
```

**Comment by rjurney** [comment]
Although the image is taking a long time to startup right now, I have resolved this issue.

**Comment by RayBrown1** [comment]
Russell,

Take a look at the errata for your book. I’ve added a set of corrections.
http://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920051619


Thanks,
Ray

Sent from Mail for Windows 10

**Comment by josenavento** [comment]
Thanks that worked for me!
