### ISSUE TITLE
Hadoop not installed on vagrant machine

### ISSUE THREAD

**Issue by JustinReboullot** [rjurney/Agile_Data_Code_2#55]
After setting up the vagrant machine, ~/hadoop directory exists but is empty. This is probably due to the fact that http://apache.osuosl.org/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz returns now a 404 error. The problem is fixed after executing the hadoop part of the manual_install.sh script.

Note that I had to execute this lother line from manual_install.sh in order for spark to works ```export SPARK_DIST_CLASSPATH=`$HADOOP_HOME/bin/hadoop classpath` ```

**Comment by MaxCaughron** [comment]
the above worked for me. just replaced the hadoop-2.7.3 with hadoop-2.7.4 in all the lines in the manual setup and it worked on the VM box

**Comment by rjurney** [comment]
Thanks, I'll fix this!

**Comment by rjurney** [comment]
I bumped the version to 2.8.2.
