### ISSUE TITLE
ec2 install getting stuck on airflow chmod?

### ISSUE THREAD

**Issue by josephshoop** [rjurney/Agile_Data_Code_2#59]
I am seeing the ec2_bootstrap.sh getting stuck on:

Running Kafka Server as a daemon ...
Installing Airflow via pip ...
Giving airflow directory to user ubuntu ...
/tmp/ec2_bootstrap.sh.log (END)

**Comment by josephshoop** [comment]
Not a big deal... just thought i would point it out. I started jupyter by running the commands in  ec2_bootstrap.sh

**Comment by rjurney** [comment]
@josephshoop Thanks! I appreciate it. I'll look at it...

**Comment by rjurney** [comment]
I think this is resolved already. Thanks for reporting it, sorry for the slow response!
