### ISSUE TITLE
kafka/bin/zookeeper-server-status.sh not found

### ISSUE THREAD

**Issue by paulozip** [rjurney/Agile_Data_Code_2#61]
I'm trying to test Kafka installation in my Vagrant instance, but when I try to run the code provide in the video (kafka/bin/zookeeper-server-status.sh), I got an directory not found error. Where's this directory?

**Comment by robnoflop** [comment]
Take a look at https://github.com/rjurney/Agile_Data_Code_2/pull/62. Perhaps that resolves your problem.

**Comment by paulozip** [comment]
Hey rob. I think it will? What script should I run to install Kafka after this commit?

**Comment by robnoflop** [comment]
**Agile_Data_Code_2/bootstrap.sh** or for clean setup delete the machine and run **vagrant up** again.

**Comment by paulozip** [comment]
Hi, Rob. It didn't work. :(

**Comment by paulozip** [comment]
Hi, Rob. What else can I do to fix this issue?

**Comment by paulozip** [comment]
@rjurney Thank you, Russel! :D

**Comment by rjurney** [comment]
@paulozip That command is missing from the latest Kafka. I think you can get by without running it. Can you try to proceed without it?

**Comment by paulozip** [comment]
Hey @rjurney. I think I can. Will the rest of the process be concluded successfully even without this specific installation?

**Comment by rjurney** [comment]
Stale.
