### ISSUE TITLE
Unable to launch ec2 instance

### ISSUE THREAD

**Issue by NavyaSreeKanakala** [rjurney/Agile_Data_Code_2#66]
Hello all,

I am unable to launch the ec2 instance r3.xlarge. I have installed awscli in my windows system via command line but unable to proceed further to launch it. Please help me in this regard.

Thanks and regards,
Navya Sree

**Comment by rjurney** [comment]
@NavyaSreeKanakala Can you please paste the error you're seeing?

**Comment by Shiyamalen** [comment]
@rjurney I am also having trouble. Any help would be greatly appreciated. I am getting the following error (IP address is blank):

 MINGW64 ~/Agile_Data_Code_2 (master)
$ ./ec2.sh
Logging operations to '/tmp/ec2.sh.log' ...

Welcome to Agile Data Science 2.0 :)

I will launch an r4.xlarge instance in the default VPC for you, using a key and security group we will create.

The utility 'jq' is required for this script to detect the hostname of your ec2 instance ...
Detecting 'jq' ...
'jq' was detected ...
Testing for security group 'agile_data_science' ...
./ec2.sh: line 35: aws: command not found
Security group 'agile_data_science' not present ...
Creating security group 'agile_data_science' ...
./ec2.sh: line 41: aws: command not found

Detecting external IP address ...
./ec2.sh: line 49: dig: command not found
Authorizing port 22 to your external IP () in security group 'agile_data_science' ...
./ec2.sh: line 54: aws: command not found

Testing for existence of keypair 'agile_data_science' and key 'agile_data_science.pem' ...
./ec2.sh: line 61: aws: command not found
Key pair 'agile_data_science' not found ...
Generating keypair called 'agile_data_science' ...
./ec2.sh: line 71: aws: command not found
Changing permissions of 'agile_data_science.pem' to 0600 ...

Detecting the default region...
./ec2.sh: line 78: aws: command not found
The default region is ''
Determining the image ID to use according to region...
The image for region '' is '' ...

Initializing EBS optimized r4.xlarge EC2 instance in region '' with security group 'agile_data_science', key name 'agile_data_science' and image id '' using the script 'aws/ec2_bootstrap.sh'
./ec2.sh: line 122: aws: command not found
Got reservation ID '' ...

Sleeping 10 seconds before inquiring to get the public hostname of the instance we just created ...
...
Awake!

Using the reservation ID to get the public hostname ...
./ec2.sh: line 145: aws: command not found
The public hostname of the instance we just created is '' ...
Writing hostname to '.ec2_hostname' ...

Now we will tag this ec2 instance and name it 'agile_data_science_ec2' ...
./ec2.sh: line 153: aws: command not found
./ec2.sh: line 154: aws: command not found

After a few minutes (for it to initialize), you may ssh to this machine via the command in red:
ssh -i ./agile_data_science.pem ubuntu@
Note: only your IP of '' is authorized to connect to this machine.

**Comment by rjurney** [comment]
Run these commands:

```bash
pip install awscli
aws configure
```

You can find more instructions on this in [README.md](README.md).
