### ISSUE TITLE
VPCResourceNotSpecified Error in AWS Script

### ISSUE THREAD

**Issue by NickyThreeNames** [rjurney/Agile_Data_Code_2#67]
I receive the following error when running the EC2 script:

"Initializing EBS optimized r4.xlarge EC2 instance in region 'us-east-1' with security group 'XXXXXx', key name 'XXXXXXX' and image id 'ami-XXXXXX' using the script 'aws/ec2_bootstrap.sh'

An error occurred (VPCResourceNotSpecified) when calling the RunInstances operation: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
Got reservation ID '' ...
"
All of the keys and security groups are the defaults from the script. I am not entirely sure how to proceed, but I am excited to continue following the video course.

Any advice is on how to proceed is appreciated. Thanks,

**Comment by rjurney** [comment]
@NickyThreeNames Sorry for the delay, I'm looking into this.

**Comment by rjurney** [comment]
@NickyThreeNames I'm not sure what is the root cause of this. Is this your personal AWS account?

**Comment by rjurney** [comment]
Stale.
