### ISSUE TITLE
issues running on ec2

### ISSUE THREAD

**Issue by peopzen** [rjurney/Agile_Data_Code_2#71]
1. registered AWS account and created a user and generated access_id and secret_key and chose a region for "aws configure" command, I passed ec2 instance installation. It took time to get everything in place.
2. run ec2_create_tunnel.sh to create connection. htt://localhost:8080 works instantly
3. ssh to instance and start jupyter-notebook, then http://localhost:8888 works fine. http://localhost:5000 is still not working
4. pyspark command works and passed test code
5. mongo agile_data_science works and passed test code

6. running ./ch02/pyspark_mongodb.py failed, says no pyspark found. "pip list" couldn't find pyspark. so "pip install pyspark", rerun, tells "sc not found". adding "from pyspark import SparkContext, sc=SparkContext()", now it generates messy errors. Frustrated.......
7. try "curl -XPUT 'localhost:9200/....", it reports "Connection refused"
elasticsearch command not found

**Comment by rjurney** [comment]
@peopzen Thanks for reporting this. Let me try to reproduce this...

**Comment by sewald101** [comment]
Experiencing exact same problem at peopzen's Step 6.

**Comment by peopzen** [comment]
Running this project on EC2 is not cheap.
Following the setup process, I ran an EC2 instance for 141 hours. It charged me $64 last month. I think I just set up free account for 12 months. How can AWS charge me? This project setup cost 20G disk space. It is still fine just under 30G of free tier. But wonder why it need 20G for such a simple project (a couple of applications and downloaded data)?

**Comment by rjurney** [comment]
@peopzen You shouldn't leave servers running when you aren't using them as it runs charges up. We need 20GB of disk because otherwise we run out while we use Spark.

**Comment by rjurney** [comment]
@sewald101 Glad you figured it out.
