### ISSUE TITLE
Connection refused error with elasticsearch

### ISSUE THREAD

**Issue by sewald101** [rjurney/Agile_Data_Code_2#73]
This looks like the same issue documented in the "closed due to staleness" issue #36. After restarting my EC2, I rerun the line in the bootstrap script to get things running:
`sudo -u ubuntu /home/ubuntu/elasticsearch/bin/elasticsearch -d`

Then I run the test line:
`curl 'localhost:9200/agile_data_science/on_time_performance/_search?q=Origin:ATL&pretty'`

I've also tried this test recommended on the elasticsearch site (http://www.elastic.co/guide/en/elasticsearch/guide/current/running-elasticsearch.html):
`curl 'http://localhost:9200/?pretty'`

And it all generates this error:
`Failed to connect to localhost port 9200: Connection refused`

I've tried:
* Adding inbound rules to the security group opening up port range 9200-9399 to ALL SOURCES (0.0.0.0/0)
* Running this different test: `curl 'http://localhost:9200/?pretty'`
* Checked and verified that my Java version is up to date

NOTHING HAS WORKED. (LOVE the idea of Agile DS 2.0, but the procedures in its text and the code in bootstrap.sh just seem to lead to brick wall after brick wall after brick wall. Frustrated.)

**Comment by arnaudbouffard** [comment]
Currently running into the same problem:

- EC2 setup
- rerun that line in the bootstrap script :
`sudo -u ubuntu /home/ubuntu/elasticsearch/bin/elasticsearch -d`
- run test `curl 'http://localhost:9200/?pretty'`
- get `Failed to connect to localhost port 9200: Connection refuse` error

will post solution if I find it

**Comment by rjurney** [comment]
@arnaudbouffard @sewald101 Sorry for the trouble, guys. I'm looking over the entire thing now.

**Comment by rjurney** [comment]
I installed Elasticsearch 5.6 and things work again.
