### ISSUE TITLE
Jupyter Server Setup Commented Out in Agile_Data_Code_2/aws/ec2_bootstrap.sh     

### ISSUE THREAD

**Issue by VassAngels** [rjurney/Agile_Data_Code_2#82]
After failing to connect to http://localhost:8888 (when http://localhost:8080 works fine) I went through ec2_bootstrap.sh to figure out how jupyter gets initialised when I spin up the aws instance and found that the 'Jupyter Server Setup' is commented out in the master branch. I thought that might be related to my problem failing to establish the localhost:8888 connection. I decided to uncomment the block and spin a new aws instance  but to no avail. This problem has been reported elsewhere here in the list of issues as it manifests as 'channel 2: open failed: connect failed: Connection refused'. Any help as to how I may be able to overcome this would be received gratefully.

**Comment by rjurney** [comment]
This has been restored, thanks.
