### ISSUE TITLE
Vagrant box  (vagrant up) Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out

### ISSUE THREAD

**Issue by thelastmor** [rjurney/Agile_Data_Code_2#83]
when I do Vagrant up I get this:

 Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'precise64' (v0) for provider: virtualbox
    default: Downloading: http://files.vagrantup.com/precise64.box
    default: Download redirected to host: hashicorp-files.hashicorp.com
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out

**Comment by pjhinton** [comment]
See the pull request here for a workaround: https://github.com/rjurney/Agile_Data_Code_2/pull/84

**Comment by rjurney** [comment]
Fixed by pull #84
